version: '3'

volumes:
    database-data:
networks:
    kaiyuanshe:

services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=${JWT_SECRET}
        volumes:
            - database-data:/var/lib/postgresql/data/
        networks:
            - kaiyuanshe
        restart: always
    openhackathon-service:
        depends_on:
            - postgres
        image: kaiyuanshe/openhackathon-service
        environment:
            - NODE_ENV=production
            - DATABASE_URL=postgres://postgres:${JWT_SECRET}@postgres:5432/postgres
            - PORT=8080
        networks:
            - kaiyuanshe
        healthcheck:
            test: ['CMD-SHELL', 'curl -f http://localhost:8080/ || exit 1']
            interval: 3s
            retries: 5
            start_period: 30s
        # labels:
        #     - autoheal=true
        restart: always
    dashpress:
        depends_on:
            - postgres
        image: kaiyuanshe/dashpress
        volumes:
            - ./dashpress/app:/app
            - ./dashpress/.config-data:/.config-data
        ports:
            - 8081:3000
        networks:
            - kaiyuanshe
        restart: always
    autoheal:
        image: willfarrell/autoheal:1.2.0
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
    caddy:
        depends_on:
            - openhackathon-service
        image: caddy
        ports:
            - 80:80
            - 443:443
        networks:
            - kaiyuanshe
        restart: always
        command: caddy reverse-proxy --from example.com --to openhackathon-service:8080
