version: '3'

volumes:
    database-data:
networks:
    freecodecamp-chengdu:

services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=${JWT_SECRET}
        volumes:
            - database-data:/var/lib/postgresql/data/
        networks:
            - freecodecamp-chengdu
        restart: always
    hop-service:
        depends_on:
            - postgres
        image: freecodecamp-chengdu/hop-service
        environment:
            - NODE_ENV=production
            - DATABASE_URL=postgres://postgres:${JWT_SECRET}@postgres:5432/postgres
            - PORT=8080
        networks:
            - freecodecamp-chengdu
        healthcheck:
            test: ['CMD-SHELL', 'curl -f http://localhost:8080/ || exit 1']
            interval: 3s
            retries: 5
            start_period: 30s
        labels:
            - autoheal=true
        restart: always
    autoheal:
        image: willfarrell/autoheal:1.2.0
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
    caddy:
        depends_on:
            - hop-service
        image: caddy
        ports:
            - 80:80
            - 443:443
        networks:
            - freecodecamp-chengdu
        restart: always
        command: caddy reverse-proxy --from example.com --to hop-service:8080
